### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by capndave** [fieryapi/node-js-samples#2]
This is my first attempt at logging in to the Fiery Server using the login function in this sample. Unfortunately, something in that function throws the following error:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```
Perhaps this relies on a deprecated version of websockets? See [https://github.com/ionic-team/ionic-cli/issues/2922]

**Comment by capndave** [comment]
Please close, I figured this out

**Comment by yusukeko** [comment]
Great to hear!

**Comment by capndave** [comment]
I have another issue that I'd love for you to check out if you're
associated with Fiery, at
https://github.com/fieryapi/node-js-samples/issues/3

Thanks!

*David Thompson*
Software Engineer
Travis Central Appraisal District
(512) 375-9134
