### ISSUE TITLE
Expired Certificate Error - Able to GET status but not jobs or info or to POST

### ISSUE THREAD

**Issue by capndave** [fieryapi/node-js-samples#3]
Hi. I'm trying to use node to communicate with fiery. So far I've been able to log in and to get the printer's status. Unfortunately, I'm unable to get jobs, info, or other information after login and am unable to post to the server. I'm getting an expired certificate error. Do I need to change the certificate settings on the Fiery Server? Is this something I can change in my code?

### My Code
```
const fs = require('fs')
const http = require('http')
const https = require('https')
const {promisify} = require('util')
const axios = require('axios')
const restler = require('restler')

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0' // Couldn't get rejectunauthorized option to work

/* Config */

// set the host name as fiery server name or ip address
var hostname = 'myServer'

// set the key to access fiery api
var apikey =
  'xxxxx'

// set the username to login to the fiery
var username = 'guest'

// set the password to login to the fiery
var password = ''

// set the full file path for job submission
var fullpath = './pdf.pdf';

/* Define Functions */

// Promisified login to the fiery
function login() {
  return new Promise(function(resolve, reject) {
    var loginjson = {
      username: username,
      password: password,
      accessrights: apikey,
    }

    var payload = JSON.stringify(loginjson)

    var options = {
      hostname: hostname,
      headers: {
        'content-type': 'application/json',
        'content-length': payload.length,
      },
      rejectunauthorized: false,
      httpAgent: new http.Agent({keepAlive: true}),  // tried this in case connection wasn't kept alive
      httpsAgent: new https.Agent({keepAlive: true}),   // tried this in case connection wasn't kept alive
    }

    axios
      .post('https://10.27.231.11/live/api/v4/login', options)
      .then(res => {
        console.log(JSON.stringify(res.data))  // successful
        const cookie = res.headers['set-cookie']
        resolve(cookie) // returns cookie to .then in promise
      })
      .catch(err => {
        reject(err)
      })
  })
}

function getJobs(cookie) {
      var options = {
      url: 'https://10.27.231.11/live/api/v4/jobs',
      method: 'get',
      headers: {
        cookie: cookie,
      },
      httpAgent: new http.Agent({keepAlive: true}),
      httpsAgent: new https.Agent({keepAlive: true}),
      rejectunauthorized: false,
    }

    axios(options)
      .then(res => {
        console.log(JSON.stringify(res.data, undefined, 2))
      })
      .catch(err => {
        console.log(err)
      })
  })
}

/* Execute Functions */

loginPromise()
  .then(cookie => {
    getJobs(cookie)
  })
  .catch(err => {
    console.log(err)
  })
```
### Results

```
{"time":"2018-09-27T10:34:49-08:00","data":{"kind":"FieryCutSheetAuthentication","item":{"authenticated":true,"fiery":true},"_links":[{"rel":"self","href":"https://10.27.231.11/live/api/v4/login"}]}}
TLSSocket {
  _tlsOptions: 
   { pipe: false,
     secureContext: SecureContext { context: SecureContext {} },
     isServer: false,
     requestCert: true,
     rejectUnauthorized: false,
     session: undefined,
     NPNProtocols: undefined,
     ALPNProtocols: undefined,
     requestOCSP: undefined },
  _secureEstablished: true,
  _securePending: false,
  _newSessionPending: false,
  _controlReleased: true,
  _SNICallback: null,
  servername: null,
  npnProtocol: undefined,
  alpnProtocol: false,
  authorized: false,
  authorizationError: 'CERT_HAS_EXPIRED',
  encrypted: true,
  _events: 
   { close: [ [Function], [Object], [Function: onClose] ],
     end: { [Function: bound onceWrapper] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     secure: [Function],
     free: [Function: onFree],
     agentRemove: [Function: onRemove],
     drain: [Function: ondrain],
     error: { [Function: bound onceWrapper] listener: [Function: freeSocketErrorListener] } },
  _eventsCount: 9,
  connecting: false,
  _hadError: false,
  _handle: 
   TLSWrap {
     _parent: 
      TCP {
        reading: [Getter/Setter],
        owner: [Circular],
        onread: null,
        onconnection: null,
        writeQueueSize: 0 },
     _parentWrap: undefined,
     _secureContext: SecureContext { context: SecureContext {} },
     reading: true,
     owner: [Circular],
     onread: [Function: onread],
     writeQueueSize: 0,
     onhandshakestart: [Function],
     onhandshakedone: [Function],
     onocspresponse: [Function],
     onerror: [Function] },
  _parent: null,
  _host: null,
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _maxListeners: undefined,
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: false,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: 
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _bytesDispatched: 219,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: undefined,
  _server: null,
  ssl: 
   TLSWrap {
     _parent: 
      TCP {
        reading: [Getter/Setter],
        owner: [Circular],
        onread: null,
        onconnection: null,
        writeQueueSize: 0 },
     _parentWrap: undefined,
     _secureContext: SecureContext { context: SecureContext {} },
     reading: true,
     owner: [Circular],
     onread: [Function: onread],
     writeQueueSize: 0,
     onhandshakestart: [Function],
     onhandshakedone: [Function],
     onocspresponse: [Function],
     onerror: [Function] },
  _requestCert: true,
  _rejectUnauthorized: false,
  parser: null,
  _httpMessage: null,
  read: [Function],
  _consuming: true,
  [Symbol(asyncId)]: -1,
  [Symbol(bytesRead)]: 0 }
```

**Comment by namcha** [comment]
Can you double check on the URL for POST login and GET jobs? The snippet you have does not use the same URL. If the POST login works, the next request for GET jobs should also work.

**Comment by capndave** [comment]
I actually changed the URLs on the github issue. They're both identical in my code so it has to be something else


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: namcha <notifications@github.com> Date: 9/27/18  4:38 PM  (GMT-06:00) To: fieryapi/node-js-samples <node-js-samples@noreply.github.com> Cc: David Thompson <capndavet@gmail.com>, Author <author@noreply.github.com> Subject: Re: [fieryapi/node-js-samples] Expired Certificate Error - Able to GET status but not jobs or info or to POST (#3) 
Can you double check on the URL for POST login and GET jobs? The snippet you have does not use the same URL. If the POST login works, the next request for GET jobs should also work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fieryapi/node-js-samples","title":"fieryapi/node-js-samples","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/fieryapi/node-js-samples"}},"updates":{"snippets":[{"icon":"PERSON","message":"@namcha in #3: Can you double check on the URL for POST login and GET jobs? The snippet you have does not use the same URL. If the POST login works, the next request for GET jobs should also work."}],"action":{"name":"View Issue","url":"https://github.com/fieryapi/node-js-samples/issues/3#issuecomment-425251574"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fieryapi/node-js-samples/issues/3#issuecomment-425251574",
"url": "https://github.com/fieryapi/node-js-samples/issues/3#issuecomment-425251574",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [fieryapi/node-js-samples] Expired Certificate Error - Able to GET status but not jobs or info or to POST (#3)",
"sections": [
{
"text": "",
"activityTitle": "**namcha**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@namcha",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"fieryapi/node-js-samples\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"fieryapi/node-js-samples\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/fieryapi/node-js-samples/issues/3#issuecomment-425251574"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 385148159\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by capndave** [comment]
I actually changed the URLs on the github issue. They're both identical in my code so it has to be something else! Once again I can login successfully and get status, but not get jobs info, just like the individual at http://fieryforums.efi.com/archive/index.php/t-6863.html?s=79b556cc34ff8f2b392fcab4e99ba686

**Comment by capndave** [comment]
So I'm able to get this to work using example functions. Looks like I'm not including the loginjson or payload objects in my request... (how do I request.write in Axios?)

**Comment by namcha** [comment]
Adding the request body via axios is done by adding the data between the url and the config parameter. It should be something like...
```js
axios.post(`https://${hostname}/live/api/v4/login`, payload, options)
```

For the certificate expiration behavior, you can try to regenerate a new self-signed certificate in configure tool (CWS → Server menu → Configure → Security → Server Certificate).

**Comment by capndave** [comment]
Awesome that is exactly what I needed! I'm going to close this issue but you may want to keep it up for others. Thanks again
